spring.application.name=Relay
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5332/relay}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:relay}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:relay_local_dev}
